events {
	worker_connections 1024;
}
worker_processes auto;
http{
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

	# This block redirects all http traffic inside the nginx container to SSL.
	# the Return 301 block tells your computer what to browse to, outside teh nginx container.
	server {
	    listen 80 default_server;

	    server_name _;
		
		# remove custom port for production
		return 301 https://$host:8443$request_uri;
	}

	# This block serves the website. If you want to test nginx http traffic, comment the above block out and uncomment the listen 80 line.
	server {
    	server_name			website;
		# listen				80;
		listen              443 ssl;
    	ssl_certificate     .ssl/cert.pem;
    	ssl_certificate_key .ssl/key.pem;
    	location / {
			proxy_pass http://website:5000;
			# proxy_pass http://localhost:5000;
		}
		keepalive_timeout   70;
	}
}